import asyncio
import json
import uuid
from typing import Dict, Any, List
import os
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import httpx
import uvicorn

# Inject FFmpeg Path
import imageio_ffmpeg
FFMPEG_EXE = imageio_ffmpeg.get_ffmpeg_exe()

app = FastAPI(title="AI Film Studio Orchestrator")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Active WebSocket connections
class ConnectionManager:
    def __init__(self):
        self.active_connections: List[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)

    def disconnect(self, websocket: WebSocket):
        self.active_connections.remove(websocket)

    async def broadcast(self, message: str):
        for connection in self.active_connections:
            await connection.send_text(message)

manager = ConnectionManager()


# ── EXTERNAL SERVICE CONFIG ──
FLUX_URL = "https://satyamashtikar--flux-kontext-fluxkontext-generate.modal.run"
WAN_URL = "https://satyamashtikar--wan2-1-i2v-wani2v-generate.modal.run"
AUDIO_URL = "https://satyamashtikar--cinematic-audio-api-serve.modal.run"


# ── MODELS ──
class BrainEnhanceReq(BaseModel):
    idea: str
    duration: int = 15

class KeyframeReq(BaseModel):
    prompt: str
    width: int = 832
    height: int = 480
    steps: int = 28

class TransitionReq(BaseModel):
    target_id: str
    image_url: str
    prompt: str
    steps: int = 40

class AudioReq(BaseModel):
    dialogue: str = ""
    music: str = ""
    sfx: str = ""
    total_duration: float = 30.0
    dialogue_start: float = 0.0
    music_volume: float = 0.4
    sfx_volume: float = 1.0

class ExportReq(BaseModel):
    format: str = "mp4"
    resolution: str = "1920x1080"
    fps: int = 24
    clips: List[str] = []

# ── HELPER FOREGROUND JOB BROADCASTER ──
async def bg_task_wrapper(job_id: str, target_type: str, target_id: str, coro, *args):
    """Wrapper to broadcast job status to all connected WebSockets."""
    await manager.broadcast(json.dumps({
        "type": "job_update",
        "job_id": job_id,
        "status": "running",
        "progress": 10,
        "message": f"Starting {target_type} generation..."
    }))
    try:
        result = await coro(*args)
        await manager.broadcast(json.dumps({
            "type": "job_complete",
            "job_id": job_id,
            "target_type": target_type,
            "target_id": target_id,
            "result": result
        }))
    except Exception as e:
        await manager.broadcast(json.dumps({
            "type": "job_error",
            "job_id": job_id,
            "target_type": target_type,
            "target_id": target_id,
            "error": str(e)
        }))

# ── ENDPOINTS ──

os.makedirs("outputs", exist_ok=True)
app.mount("/outputs", StaticFiles(directory="outputs"), name="outputs")

@app.get("/health")
async def health_check():
    return {"status": "ok"}

@app.get("/api/health")
async def api_health_check():
    return {"status": "ok"}

@app.post("/api/brain/enhance")
async def enhance_idea(req: BrainEnhanceReq):
    import asyncio
    from gemma_video_pipeline import generate_video_json
    
    loop = asyncio.get_running_loop()
    try:
        # Run the gemma generation in a background thread so we don't block the asyncio event loop
        result = await loop.run_in_executor(None, generate_video_json, req.idea, req.duration)
        
        if result and len(result) > 0:
            # We take the first scene since the frontend expects a single scene object
            return result[0]
        else:
            raise Exception("No scenes generated by Gemma.")
    except Exception as e:
        print(f"Error in enhance_idea: {e}")
        return {
            "description": f"Error cinematic rendition of: {req.idea}",
            "keyframe_prompt": f"Wide establishing shot. {req.idea}",
            "clips": [{"clip": 1, "transition_prompt": "Camera pans.", "music": "Drone", "sound_effect": "Wind"}],
            "dialogue_prompt": [{"clip": 1, "dialogue": "There was an error."}]
        }

@app.post("/api/keyframes/generate")
async def generate_keyframe(req: KeyframeReq):
    filename = f"kf_{uuid.uuid4().hex[:8]}.jpeg"
    filepath = os.path.join("outputs", filename)
    
    # We use a base image file to mutate
    init_img = "WhatsApp Image 2026-04-05 at 22.46.57.jpeg"
    with open(init_img, "rb") as f:
        img_data = f.read()

    try:
        async with httpx.AsyncClient(follow_redirects=True) as client:
            res = await client.post(
                FLUX_URL,
                data={"prompt": req.prompt, "num_inference_steps": req.steps, "width": req.width, "height": req.height},
                files={"image_file": (os.path.basename(init_img), img_data, "image/jpeg")},
                timeout=300.0
            )
            res.raise_for_status()
            with open(filepath, "wb") as f:
                f.write(res.content)
        return {"url": f"/outputs/{filename}", "job_id": f"kf_{uuid.uuid4().hex[:8]}"}
    except Exception as e:
        print(f"Keyframe API Error: {e}")
        return {"url": "https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?q=80&w=832&auto=format&fit=crop", "job_id": f"kf_{uuid.uuid4().hex[:8]}"}

@app.post("/api/transitions/generate")
async def generate_transition(req: TransitionReq):
    job_id = f"job_tr_{uuid.uuid4().hex[:8]}"

    async def _do_tr():
        filename = f"tr_{uuid.uuid4().hex[:8]}.mp4"
        filepath = os.path.join("outputs", filename)

        if req.image_url and "outputs/" in req.image_url:
            local_img = os.path.join("outputs", req.image_url.split("outputs/")[-1])
        else:
            local_img = "WhatsApp Image 2026-04-05 at 22.46.57.jpeg"

        try:
            with open(local_img, "rb") as f:
                img_data = f.read()

            async with httpx.AsyncClient(follow_redirects=True) as client:
                res = await client.post(
                    WAN_URL,
                    data={"prompt": req.prompt, "num_inference_steps": req.steps},
                    files={"image_file": (os.path.basename(local_img), img_data, "image/jpeg")},
                    timeout=900.0
                )
                res.raise_for_status()
                with open(filepath, "wb") as f:
                    f.write(res.content)
            return {"url": f"/outputs/{filename}"}
        except Exception as e:
            print(f"Transition API Error: {e}")
            return {"url": "https://www.w3schools.com/html/mov_bbb.mp4"}

    asyncio.create_task(bg_task_wrapper(job_id, "transition", req.target_id, _do_tr))
    return {"job_id": job_id, "target_id": req.target_id}

@app.post("/api/audio/generate")
async def generate_audio(req: AudioReq):
    job_id = f"job_au_{uuid.uuid4().hex[:8]}"
    target_id = str(uuid.uuid4())

    async def _do_au():
        try:
            async with httpx.AsyncClient(follow_redirects=True) as client:
                res = await client.post(f"{AUDIO_URL}/generate", json={
                    "dialogue": req.dialogue,
                    "music": req.music,
                    "sfx": req.sfx,
                    "total_duration": req.total_duration,
                    "dialogue_start": req.dialogue_start,
                    "music_volume": req.music_volume,
                    "sfx_volume": req.sfx_volume
                }, timeout=120.0)
                res.raise_for_status()
                data = res.json()
                filename = data.get("filename", "")
                download_url = f"{AUDIO_URL}/download/{filename}"
                return {"url": download_url}
        except Exception as e:
            print(f"Audio fallback due to error: {e}")
            await asyncio.sleep(1)
            return {"url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"}

    asyncio.create_task(bg_task_wrapper(job_id, "audio", target_id, _do_au))
    return {"job_id": job_id, "target_id": target_id}

@app.post("/api/export")
async def export_film(req: ExportReq):
    job_id = f"exp_{uuid.uuid4().hex[:8]}"
    target_id = "export_scene"

    async def _do_exp():
        # Auto-discover clips if none provided from frontend
        clips_to_process = req.clips or []
        if not clips_to_process:
            # get all transition mp4s from outputs folder sorted by timestamp
            import glob
            files = glob.glob("outputs/tr_*.mp4")
            files.sort(key=os.path.getmtime)
            for file in files:
                clips_to_process.append(f"/{file.replace(chr(92), '/')}")

        if not clips_to_process:
            await asyncio.sleep(2)
            return {"url": "https://www.w3schools.com/html/mov_bbb.mp4", "download_url": "https://www.w3schools.com/html/mov_bbb.mp4"}
            
        list_file = os.path.join("outputs", f"concat_list_{job_id}.txt")
        final_video = os.path.join("outputs", f"final_export_{job_id}.mp4")
        
        with open(list_file, "w") as f:
            for clip_url in clips_to_process:
                # clip_url might be /outputs/tr_xxxx.mp4
                if "outputs/" in clip_url:
                    local_path = os.path.join("outputs", clip_url.split("outputs/")[-1])
                    if os.path.exists(local_path):
                        f.write(f"file '{os.path.abspath(local_path)}'\n")

        import subprocess
        print(f"Concatenating export to {final_video}")
        cmd = [FFMPEG_EXE, "-f", "concat", "-safe", "0", "-i", list_file, "-c", "copy", "-y", final_video]
        try:
            subprocess.run(cmd, check=True)
        finally:
            if os.path.exists(list_file):
                os.remove(list_file)
                
        # the Vite proxy expects /outputs prefix
        frontend_url = f"/outputs/final_export_{job_id}.mp4"
        return {"url": frontend_url, "download_url": frontend_url}

    asyncio.create_task(bg_task_wrapper(job_id, "export", target_id, _do_exp))
    return {"job_id": job_id}


@app.post("/api/generate_full")
async def generate_full(req: BrainEnhanceReq):
    job_id = f"job_full_{uuid.uuid4().hex[:8]}"
    target_id = str(uuid.uuid4())
    
    async def _do_gen():
        import e2e_pipeline
        loop = asyncio.get_running_loop()
        def on_progress(msg, progress):
            payload = json.dumps({
                "type": "job_update",
                "job_id": job_id,
                "status": "running",
                "progress": progress,
                "message": msg
            })
            asyncio.run_coroutine_threadsafe(manager.broadcast(payload), loop)
            
        final_video_path = await asyncio.to_thread(e2e_pipeline.run_e2e_pipeline, req.idea, req.duration, on_progress)
        if final_video_path and os.path.exists(final_video_path):
            import shutil
            fname = os.path.basename(final_video_path)
            shutil.copy(final_video_path, os.path.join("outputs", fname))
            url = f"/outputs/{fname}"
            return {"url": url, "download_url": url}
        raise Exception("E2E Pipeline failed to output a final video.")
        
    asyncio.create_task(bg_task_wrapper(job_id, "export", target_id, _do_gen))
    return {"job_id": job_id}

@app.post("/api/jobs/{job_id}/cancel")
async def cancel_job(job_id: str):
    # In a real system, you'd cancel the actual bg task / modal run.
    # For now, we accept the request so the frontend can clear it from UI.
    return {"status": "cancelled", "job_id": job_id}

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await manager.connect(websocket)
    try:
        while True:
            data = await websocket.receive_text()
            # Handle frontend requests if needed
    except WebSocketDisconnect:
        manager.disconnect(websocket)


if __name__ == "__main__":
    print("Starting Orchestrator on ws://localhost:8000 and http://localhost:8000")
    uvicorn.run(app, host="0.0.0.0", port=8000)
